apiVersion: apps/v1
kind: Deployment
metadata:
  name: junior-devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: junior-devops-lab
  template:
    metadata:
      labels:
        app: junior-devops-lab
    spec:
      containers:
        - name: web
          image: junior-devops-lab:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
